
resources:
  - url: /local/scheduler-card/scheduler-card.js
    type: module

views:
  - title: Example
    cards:
      - type: custom:scheduler-card
        groups:
          lights:
            icon: lamp
            domains: [light]
          covers:
            icon: window-shutter-open
            domains: [cover]
          heating:
            icon: home-thermometer-outline
            domains: [climate]
          cleaning:
            icon: broom
            domains: [vacuum]
          automations:
            icon: home-automation
            domains: [script]

        domains:
          light:
            actions:
              - icon: lightbulb-on-outline
                service: turn_on
              - icon: lightbulb-off-outline
                service: turn_off
            icon: lightbulb
          cover:
            actions:
              - icon: window-shutter-open
                service: open_cover
                name: open
              - icon: window-shutter-close
                service: close_cover
                name: close

        entities:
          light.garden_lights:
            icon: coach-lamp
          light.dining_lights:
            icon: ceiling-light
            actions:
              - icon: lightbulb-outline
                service: turn_on
                service_data: {brightness: 100}
                name: dim to 40%
          light.hall_lamp:
            icon: lamp
          cover.living_room:
            icon: blinds
            name: living room blinds
          cover.bedroom:
            icon: window-open-variant
            name: bedroom curtains
          climate.mqtt_thermostat:
            icon: thermostat
            name: house thermostat
            actions:
              - icon: thermometer-chevron-down
                service: climate.set_temperature
                service_data: {temperature: 10}
                name: set to 10C
              - icon: thermometer-chevron-up
                service: climate.set_temperature
                service_data: {temperature: 22}
                name: set to 22C
          vacuum.roborock:
            icon: robot-vacuum
            name: robot vacuum
            actions:
              - icon: stove
                name: clean kitchen
                service: xiaomi_miio.vacuum_clean_zone
                service_data: {entity_id: vacuum.roborock, zone: [[22896,18514,25800,20614]], repeats: 1}
              - icon: sofa
                name: clean living room
                service: xiaomi_miio.vacuum_clean_zone
                service_data: {entity_id: vacuum.roborock, zone: [[20250,18514,23100,22714], [20250,22714,23360,27000], [23150,20814,25960,27200]], repeats: 1}
              - icon: door-closed
                name: clean entrance
                service: xiaomi_miio.vacuum_clean_zone
                service_data: {entity_id: vacuum.roborock, zone: [[25960,20814,30300,22000], [27060,19350,28880,20814]], repeats: 1}
          script.battery_check:
            icon: battery-alert-variant-outline
            name: check battery levels
            actions:
              - icon: play-circle-outline
                service: turn_on
                name: start
          script.trigger_backup:
            icon: cloud-upload-outline
            name: backup hass
            actions:
              - icon: play-circle-outline
                service: turn_on
                name: start
